### ISSUE TITLE
Settings.define 'setting', :environment => 'ENV_VAR'

### ISSUE THREAD

**Issue by orlin** [infochimps-labs/configliere#1]
The title does not work.  The following does:
Settings.environment_variables 'ENV_VAR' => 'setting'

Also, the README says Settings.use_environment (no such method) - which changed to environment_variables?

**Comment by mrflip** [comment]
Changed interface and reconciled documentation n light of this and other issues.  

You should now use

```
Settings.env_vars :setting => 'ENV_VAR'
```

or 

```
Settings.define :setting, :env_var => 'ENV_VAR'
```

See [examples/env_var_script.rb](http://github.com/mrflip/configliere/blob/master/examples/env_var_script.rb) for a demonstration

Notice that these simple keys must be symbols, not strings.
