### ISSUE TITLE
Configliere::Param isn't accessible by ['foo']

### ISSUE THREAD

**Issue by kornypoet** [infochimps-labs/configliere#11]
When a config file is read in, and the Settings object is returned, the Settings object is not accessible by strings, i.e.
Settings['key'] does not return the value. Current implementation allows access only by using symbols, i.e. Settings[:key]

**Comment by mrflip** [comment]
That's not what I'm seeing. Here's a file that has some string and some symbol keys:

``` yaml
--- 
:dest_time: 1985-11-05
:delorean: 
  :power_source: lightning
  'quantity':     1.21 jiggawats
'heavy':     true
'driver':     marty
```

Here I am accessing those with perfect indifference as to their symbol or string nature:

```
>> Settings.read('/tmp/foo.yaml')
=> {:dest_time=>#<Date: 1985-11-05 (4892749/2,0,2299161)>, :delorean=>{:power_source=>"lightning", :quantity=>"1.21 jiggawats"}, :heavy=>true, :driver=>"doc brown"}
>> Settings['heavy']
=> true
>> Settings['driver']
=> "doc brown"
>> Settings[:driver]
=> "doc brown"
>> Settings[:delorean][:quantity]
=> "1.21 jiggawats"
>> Settings[:delorean]['power_source']
=> "lightning"
```

The keys have been properly coerced to symbols, and the subhashes to Configliere::Param objects -- but as you saw, perfectly referenceable as a hash.

``` ruby
p Settings
{:dest_time=>"#<Date: 1985-11-05 (4892749/2,0,2299161)>", :delorean=>{:power_source=>"lightning", :quantity=>"1.21 jiggawats"}, :heavy=>true, :driver=>"doc brown"}
p Settings[:delorean].class
Configliere::Param
```

Can you paste in a failing YAML file and code snippet?

**Comment by dhruvbansal** [comment]
yes this is an issue, merge! doesn't do the proper conversions.  use deep_merge! in place as a workaround till fixed.
