### ISSUE TITLE
:encrypted => true

### ISSUE THREAD

**Issue by orlin** [infochimps-labs/configliere#2]
Encrypted parameters don't get saved.  Example:

Configliere.use :config_file, :define
Settings 'password' => 'plaintext'
Settings.define 'password', :required => true, :encrypted => true
Settings.resolve!
Settings.save!('file.yml')
# anything missing?

**Comment by mrflip** [comment]
You have to use symbol keys to name parameters (except dotted params of course, which are expanded to symbol keys).

This should work:

```
require 'configliere'
Settings.use :config_file, :define, :encrypted, :encrypt_pass => 'hi_mom'
Settings :password => 'plaintext'
Settings.define :password, :required => true, :encrypted => true
Settings.resolve!
Settings.save!('/tmp/encrypted_param_test.yml')
```

See [examples/encrypted_script.rb](http://github.com/mrflip/configliere/blob/master/examples/encrypted_script.rb) for a demonstration of encrypted parameters.
