### ISSUE TITLE
Error when trying to use Settings.finally

### ISSUE THREAD

**Issue by arvicco** [infochimps-labs/configliere#6]
C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/configliere-0.3.4/lib/configliere/define.rb:173:in `method_missing': undefined method`finally' for #Configliere::Param:0x1a90490 (NoMethodError)
        from bin/vcl_gui_config:17:in `<main>'
## Code:

require 'configliere'
Settings.use :commandline, :config_file

Settings :client => {:ini => CLIENT_INI,
                     :name => 'vcl_gui_config'}

Settings.read BASE_DIR + 'config/vcl_client.yml'

Settings.finally do |c|
  p [self, 'finally', c[:client], c.client]
end

Settings.resolve!

**Comment by arvicco** [comment]
Settings are read and resolved without any problems if not using 'finally'

**Comment by mrflip** [comment]
(Apologies: somehow GitHub is eating my emails. trying again...)

Can you try adding :config_block to the inclusions?

Settings.use :commandline, :config_file, :config_block

On Fri, Apr 29, 2011 at 1:04 PM, arvicco <
reply@reply.github.com>wrote:

> C:/Dev/ruby/lib/ruby/gems/1.9.1/gems/configliere-0.3.4/lib/configliere/define.rb:173:in
> `method_missing': undefined method`finally' for
> #Configliere::Param:0x1a90490 (NoMethodError)
>        from bin/vcl_gui_config:17:in `<main>'
> 
> ## Code:
> 
> require 'configliere'
> Settings.use :commandline, :config_file
> 
> Settings :client => {:ini => CLIENT_INI,
>                     :name => 'vcl_gui_config'}
> 
> Settings.read BASE_DIR + 'config/vcl_client.yml'
> 
> Settings.finally do |c|
>  p [self, 'finally', c[:client], c.client]
> end
> 
> Settings.resolve!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mrflip/configliere/issues/6

## 

infochimps.com - discover data

**Comment by arvicco** [comment]
I added inclusion as per your suggestion, now #finally works, but c inside block is nil:

---

bin/zmq_adapter_config:22:in `block in <main>': undefined method`[]' for nil:NilClass (NoMethodError)

**Comment by mrflip** [comment]
Fixed by SHA:2974476aa375ddd0935e51d1831f8e2574dd3952
